-- =============================================================================
-- SentinelAI :: initial schema
--
-- Conventions:
--   * All primary keys are UUIDs generated by the application.
--   * All timestamps are `timestamptz` and are written in UTC. Event *time*
--     (`occurred_at`) is kept strictly separate from *ingestion* time
--     (`received_at`) so that late-arriving events do not rewrite history.
--   * Human readable references (INC-1042) are exposed to clients; the UUID
--     remains the join key.
-- =============================================================================

create sequence incident_reference_seq start 1000;
create sequence analysis_reference_seq start 200;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
create table app_users (
    id            uuid primary key,
    name          varchar(200) not null,
    email         varchar(320) not null,
    password_hash varchar(200) not null,
    role          varchar(20)  not null,
    created_at    timestamptz  not null default now(),
    constraint uq_users_email unique (email),
    constraint ck_users_role check (role in ('ADMIN', 'ENGINEER', 'VIEWER'))
);

-- -----------------------------------------------------------------------------
-- services (the monitored systems that emit events)
-- -----------------------------------------------------------------------------
create table services (
    id           uuid primary key,
    name         varchar(120) not null,
    environment  varchar(40)  not null,
    health_status varchar(20) not null default 'HEALTHY',
    owner_team   varchar(120),
    created_at   timestamptz  not null default now(),
    constraint uq_services_name_env unique (name, environment),
    constraint ck_services_health check (health_status in ('HEALTHY', 'DEGRADED', 'UNHEALTHY', 'UNKNOWN'))
);

-- -----------------------------------------------------------------------------
-- events (immutable ingest log)
-- -----------------------------------------------------------------------------
create table events (
    id              uuid primary key,
    -- Idempotency scope: a producer's event id is unique within its scope.
    source_scope    varchar(80)  not null default 'default',
    source_event_id varchar(200) not null,
    service_id      uuid         not null references services (id),
    event_type      varchar(40)  not null,
    severity        varchar(20)  not null,
    message         varchar(4000) not null,
    -- Normalised form of `message`; repeated messages collapse to one signature.
    error_signature varchar(200),
    occurred_at     timestamptz  not null,
    received_at     timestamptz  not null default now(),
    metadata_json   jsonb        not null default '{}'::jsonb,
    constraint uq_events_source unique (source_scope, source_event_id),
    constraint ck_events_severity check (severity in ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
);

-- Evidence retrieval for a service over a time window.
create index idx_events_service_occurred on events (service_id, occurred_at desc);
create index idx_events_occurred on events (occurred_at desc);
create index idx_events_service_signature on events (service_id, error_signature);

-- -----------------------------------------------------------------------------
-- detection_rules (configurable, data-driven thresholds)
-- -----------------------------------------------------------------------------
create table detection_rules (
    id                  uuid primary key,
    code                varchar(80)  not null,
    name                varchar(200) not null,
    description         text,
    -- Events whose `event_type` matches are candidates for this rule.
    event_type          varchar(40)  not null,
    -- Key looked up in events.metadata_json; compared with `comparator`.
    -- A NULL metric_key means "every event of this type matches".
    metric_key          varchar(80),
    comparator          varchar(6)   not null,
    threshold           double precision,
    -- Severity assigned to the incident when this rule fires.
    severity            varchar(20)  not null default 'MEDIUM',
    -- Seconds of history the rule considers when computing windowed metrics.
    window_seconds      int          not null default 60,
    -- Seconds during which a repeat of the same fingerprint updates the open
    -- incident instead of being dropped as a duplicate alert.
    dedupe_window_seconds int        not null default 300,
    -- Groups rules whose symptoms should correlate into one incident.
    correlation_group   varchar(80),
    enabled             boolean      not null default true,
    created_at          timestamptz  not null default now(),
    constraint uq_detection_rules_code unique (code),
    constraint ck_detection_rules_comparator check (comparator in ('GT', 'GTE', 'LT', 'LTE', 'EQ', 'NEQ')),
    constraint ck_detection_rules_severity check (severity in ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    constraint ck_detection_rules_window check (window_seconds > 0 and dedupe_window_seconds > 0)
);

create index idx_detection_rules_enabled on detection_rules (enabled) where enabled;

-- -----------------------------------------------------------------------------
-- incidents
--
-- `timeline_seq` is an atomic per-incident counter. It gives clients a
-- monotonic cursor for reconnect recovery without a second round trip.
-- `version` drives JPA optimistic locking so two engineers cannot silently
-- overwrite each other's assignment.
-- -----------------------------------------------------------------------------
create table incidents (
    id                    uuid primary key,
    reference             varchar(40)  not null,
    fingerprint           varchar(64)  not null,
    title                 varchar(300) not null,
    service_id            uuid         not null references services (id),
    severity              varchar(20)  not null,
    status                varchar(20)  not null,
    assigned_to           uuid         references app_users (id),
    detection_rule_code   varchar(80),
    error_signature       varchar(200),
    correlation_group     varchar(80),
    -- Evidence that caused the incident to be opened, as text.
    trigger_evidence      text,
    first_seen_at         timestamptz  not null,
    last_seen_at          timestamptz  not null,
    -- Last time a repeat occurrence was surfaced (timeline entry + broadcast).
    -- Occurrences arriving inside a rule's dedupe window are counted into
    -- event_count but do not each generate a timeline entry or a live update.
    last_notified_at      timestamptz,
    event_count           int          not null default 0,
    timeline_seq          bigint       not null default 0,
    version               bigint       not null default 0,
    resolved_at           timestamptz,
    resolved_root_cause   text,
    preventive_actions    text,
    constraint uq_incidents_reference unique (reference),
    constraint ck_incidents_status check (status in ('OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED')),
    constraint ck_incidents_severity check (severity in ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    constraint ck_incidents_window check (last_seen_at >= first_seen_at),
    constraint ck_incidents_event_count check (event_count >= 0)
);

-- Dashboard feed: filter by status/severity, order by most recent activity.
create index idx_incidents_feed on incidents (status, severity, last_seen_at desc);
create index idx_incidents_service on incidents (service_id, last_seen_at desc);
-- Partial index over open work only: the hot path for correlation lookups.
create index idx_incidents_active_fingerprint on incidents (fingerprint) where status <> 'RESOLVED';
create index idx_incidents_active_service on incidents (service_id, status) where status <> 'RESOLVED';
create index idx_incidents_assigned on incidents (assigned_to, status) where assigned_to is not null;
create index idx_incidents_last_seen on incidents (last_seen_at desc);

-- -----------------------------------------------------------------------------
-- incident_events (evidence linking)
-- -----------------------------------------------------------------------------
create table incident_events (
    incident_id       uuid        not null references incidents (id) on delete cascade,
    event_id          uuid        not null references events (id) on delete cascade,
    relationship_type varchar(30) not null,
    linked_at         timestamptz not null default now(),
    primary key (incident_id, event_id),
    constraint ck_incident_events_relationship check (relationship_type in ('TRIGGER', 'REPEAT', 'CORRELATED'))
);

create index idx_incident_events_event on incident_events (event_id);

-- -----------------------------------------------------------------------------
-- ai_analyses
-- -----------------------------------------------------------------------------
create table ai_analyses (
    id                     uuid primary key,
    reference              varchar(40) not null,
    incident_id            uuid        not null references incidents (id) on delete cascade,
    model_name             varchar(120) not null,
    prompt_version         varchar(40)  not null,
    status                 varchar(20)  not null,
    attempt_count          int          not null default 0,
    trigger_reason         varchar(60),
    analysis_json          jsonb,
    -- Exactly what was sent to the model, so a hypothesis can be audited.
    evidence_snapshot_json jsonb,
    usage_json             jsonb,
    requested_by           uuid         references app_users (id),
    created_at             timestamptz  not null default now(),
    started_at             timestamptz,
    completed_at           timestamptz,
    duration_ms            bigint,
    error_code             varchar(60),
    error_message          varchar(1000),
    constraint uq_ai_analyses_reference unique (reference),
    constraint ck_ai_analyses_status check (status in ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'REJECTED'))
);

create index idx_ai_analyses_incident on ai_analyses (incident_id, created_at desc);
-- Partial index: the job processor only ever scans unfinished work.
create index idx_ai_analyses_pending on ai_analyses (created_at) where status in ('QUEUED', 'RUNNING');

-- -----------------------------------------------------------------------------
-- incident_timeline (append-only audit log)
-- -----------------------------------------------------------------------------
create table incident_timeline (
    id          uuid primary key,
    incident_id uuid        not null references incidents (id) on delete cascade,
    actor_id    uuid        references app_users (id),
    event_type  varchar(40) not null,
    summary     varchar(500),
    payload_json jsonb      not null default '{}'::jsonb,
    sequence_no bigint      not null,
    created_at  timestamptz not null default now(),
    constraint uq_timeline_incident_seq unique (incident_id, sequence_no)
);

create index idx_timeline_incident on incident_timeline (incident_id, sequence_no);
create index idx_timeline_created on incident_timeline (created_at desc);
